### ISSUE TITLE
Other institutions are sending support requests to UF

### ISSUE THREAD

**Issue by pbchase** [ctsit/warn_users_of_pending_suspension#12]
Other institutions using WUPS are sending support requests to UF.  The problem flows from this line: https://github.com/ctsit/warn_users_of_pending_suspension/blob/0593f4f9ee75800190fdf9650cd91080531b16bb/ExternalModule.php#L110

We assume the global variable $project_contact_email is correctly populated, but apparently that’s not always the case. Please design a solution that will get us out of this conundrum. I'm not sure what that looks like, but not everyone is using REDCap as we do and it's causing us issues.

**Comment by ChemiKyle** [comment]
Hi @pbchase, the _developer_ section of the README states `$project_contact_email` is populated via the "Email Address of REDCap Administrator" field under Control Center > General Configuration. This should probably be moved to _Configuration_.

I imagine a good solution may be to allow admins to set an email in the Control Center config that defaults to `$project_contact_email` if blank. If "Email Address of REDCap Administrator" is not set, the email should simply fail to send; to be nice, the cron job could return a message that these fields are not set properly.

**Comment by ChemiKyle** [comment]
Addressed by PR #14  

Due to an error in scoping of the `$project_contact_email`, unless users had set the "Universal 'FROM'" option, all emails sent by this module would have appeared to come from CTSI-REDCAP-SUPPORT-L@lists.ufl.edu.
