### ISSUE TITLE
Activation link broken (email preview not to be trusted)

### ISSUE THREAD

**Issue by marlycormar** [ctsit/warn_users_of_pending_suspension#15]
Even though the activation link in the email preview in REDCap looks well formatted, the actual email is not:

> Due to inactivity, your REDCap account will be suspended in 30 days on 2019-10-18. If you want to avoid account suspension, please click on this link: [[activation_link]]REDCap account extension.

**Comment by ChemiKyle** [comment]
Hi @marlycormar, actually in this case it's the email body template that is out of date. `[activation_link]` was removed in 9a549dc, when we got rid of the WUPS page and moved to updating their activity via the homepage.
