### ISSUE TITLE
Could the plugin page in the email redirect to the the main redcap url?

### ISSUE THREAD

**Issue by pbchase** [ctsit/warn_users_of_pending_suspension#3]
Could the plugin page referenced in the email redirect to the the main redcap url? The user is left on a white feature-less screen.  It would be better if they were redirected to the main redcap page and saw a temporary green box popup that had the same message that the plugin currently shows.

**Comment by marlycormar** [comment]
That is a good idea and is indeed possible to do. I did most of the work already (it may be tested) but I need to add the necessary steps to log the db changes. I will add a PR once this is done.

**Comment by marlycormar** [comment]
@pbchase PR#4 should take care of this issue.
