### ISSUE TITLE
Add "Send test email" feature to WUPS

### ISSUE THREAD

**Issue by tlstoffs** [ctsit/warn_users_of_pending_suspension#8]
Can we add a feature to have admins be able to preview the email message so we can see how it's formatted and looks to the users?

Dear [user_firstname] [user_lastname], <br><br>

Due to inactivity, your REDCap account will be suspended in [days_until_suspension] days on [suspension_date].
If you want to avoid account suspension, please just login to redcap at https://redcap.ctsi.ufl.edu/redcap/<br><br>

Regards,<br>
REDCap Support Team.

If your account does get suspended, please submit a service request via the REDCap website to have it re-activated.

**Comment by ChemiKyle** [comment]
@tlstoffs As we found on Friday, I have a fix for this; are you familiar with testing pull requests from github?

**Comment by marlycormar** [comment]
Fixed by PR #9.
